[package]
name = "chess_realm"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.2", features = ["persistence"] }
rfd = "0.16.0"
serde = { version = "1.0.228", features = ["derive"] }
